name       : minidlna
version    : 1.1.5
release    : 7
source     :
    - http://internode.dl.sourceforge.net/project/minidlna/minidlna/1.1.5/minidlna-1.1.5.tar.gz : 8477ad0416bb2af5cd8da6dde6c07ffe1a413492b7fe40a362bc8587be15ab9b
license    : GPL-2.0
component  : network.util
summary    : ReadyMedia (previously MiniDLNA) is server software that serves media
    files (music, pictures, and video) to clients on a network.
description: |
    ReadyMedia (previously MiniDLNA) is server software with the aim of being fully compliant with DLNA/UPnP clients. The MiniDNLA daemon serves media files (music, pictures, and video) to clients on a network. Example clients include applications such as totem and xbmc, and devices such as portable media players, Smartphones, Televisions, and gaming systems (such as PS3 and Xbox 360).
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libavutil)
    - pkgconfig(libexif)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
    - libid3tag-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # TODO: Make stateless!
    install -D -m 00644 minidlna.conf $installdir/etc/minidlna.conf
    install -D -m 00644 $pkgfiles/minidlna.tmpfiles $installdir/%libdir%/tmpfiles.d/minidlna.conf
    install -D -m 00644 $pkgfiles/minidlna.sysusers $installdir/%libdir%/sysusers.d/minidlna.conf
    install -D -m 00644 $pkgfiles/minidlna.service $installdir/%libdir%/systemd/system/minidlna.service
