name       : minidlna
version    : 1.2.1
release    : 9
source     :
    - https://kent.dl.sourceforge.net/project/minidlna/minidlna/1.2.1/minidlna-1.2.1.tar.gz : 67388ba23ab0c7033557a32084804f796aa2a796db7bb2b770fb76ac2a742eec
license    : GPL-2.0-or-later
component  : network.util
summary    : ReadyMedia (previously MiniDLNA) is server software that serves media files (music, pictures, and video) to clients on a network
description: |
    ReadyMedia (previously MiniDLNA) is server software with the aim of being fully compliant with DLNA/UPnP clients. The MiniDNLA daemon serves media files (music, pictures, and video) to clients on a network. Example clients include applications such as totem and xbmc, and devices such as portable media players, Smartphones, Televisions, and gaming systems (such as PS3 and Xbox 360).
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(id3tag)
    - pkgconfig(libavutil)
    - pkgconfig(libexif)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
    # TODO: Make stateless!
    install -D -m 00644 minidlna.conf $installdir/etc/minidlna.conf
    install -D -m 00644 $pkgfiles/minidlna.tmpfiles $installdir/%libdir%/tmpfiles.d/minidlna.conf
    install -D -m 00644 $pkgfiles/minidlna.sysusers $installdir/%libdir%/sysusers.d/minidlna.conf
    install -D -m 00644 $pkgfiles/minidlna.service $installdir/%libdir%/systemd/system/minidlna.service
