name       : minidlna
version    : 1.3.3
release    : 17
source     :
    - https://ixpeering.dl.sourceforge.net/project/minidlna/minidlna/1.3.3/minidlna-1.3.3.tar.gz : 39026c6d4a139b9180192d1c37225aa3376fdf4f1a74d7debbdbb693d996afa4
homepage   : https://sourceforge.net/projects/minidlna/
license    : GPL-2.0-or-later
component  : network.util
summary    : ReadyMedia (previously MiniDLNA) is server software that serves media files (music, pictures, and video) to clients on a network
description: |
    ReadyMedia (previously MiniDLNA) is server software with the aim of being fully compliant with DLNA/UPnP clients. The MiniDNLA daemon serves media files (music, pictures, and video) to clients on a network. Example clients include applications such as totem and xbmc, and devices such as portable media players, Smartphones, Televisions, and gaming systems (such as PS3 and Xbox 360).
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(id3tag)
    - pkgconfig(libavutil)
    - pkgconfig(libexif)
    - pkgconfig(libturbojpeg)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
rundeps    :
    - libid3tag
setup      : |
    %patch -p1 < $pkgfiles/0001-Add-stateless-configuration-support.patch
    %configure
build      : |
    %make
install    : |
    %make_install
    install -Dm00644 $pkgfiles/minidlna.conf $installdir/usr/share/defaults/etc/minidlna.conf
    install -Dm00644 $pkgfiles/minidlna.tmpfiles $installdir/%libdir%/tmpfiles.d/minidlna.conf
    install -Dm00644 $pkgfiles/minidlna.sysusers $installdir/%libdir%/sysusers.d/minidlna.conf
    install -Dm00644 $pkgfiles/minidlna.service $installdir/%libdir%/systemd/system/minidlna.service
