name       : minidlna
version    : 1.1.4
release    : 2
source     :
    - http://internode.dl.sourceforge.net/project/minidlna/minidlna/1.1.4/minidlna-1.1.4.tar.gz : 9814c04a2c506a0dd942c4218d30c07dedf90dabffbdef2d308a3f9f23545314
license    : GPL-2.0
component  : network.util
summary    : ReadyMedia (previously MiniDLNA) is server software that serves media
    files (music, pictures, and video) to clients on a network.
description: |
    ReadyMedia (previously MiniDLNA) is server software with the aim of being fully compliant with DLNA/UPnP clients. The MiniDNLA daemon serves media files (music, pictures, and video) to clients on a network. Example clients include applications such as totem and xbmc, and devices such as portable media players, Smartphones, Televisions, and gaming systems (such as PS3 and Xbox 360).
builddeps  :
    - pkgconfig(flac)
    - pkgconfig(libavutil)
    - pkgconfig(libexif)
    - pkgconfig(sqlite3)
    - pkgconfig(vorbis)
    - libid3tag-devel
    - libjpeg-turbo-devel
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
